title = "The Way of the Crab"
description = "A podcast where two Rustaceans set out to make a game."
base_url = "https://wayofthecrab.com"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
external_links_target_blank = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
