title = "The Way of the Crab"
description = "A podcast where two Rustaceans set out to make a game. In each episode, we talk about what we've been working on using the Rust programming language as well as other topics that have been on our mind or our listeners have asked about."
base_url = "https://wayofthecrab.com"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
external_links_target_blank = true

[extra]
# Put all your custom variables here
