on: push
name: Build Website
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz
      - name: Build
        run: |
          ./zola build

      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: wayofthecrab.com
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3

      - name: Prepare SSH
        run: |
          mkdir ~/.ssh
          chmod 0700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 0600 ~/.ssh/*
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

      - name: Rsync
        run:
          rsync -avzdn public/ wotc@wayofthecrab.com:public/